package ui.enums;

public enum UI_EVENT {
	// Sammlung der UI EVENTS
	ORDERS, PUSH_BACK_BUTTON, CHECK_STATUS, SEARCH, INFO, HOUSES, ORDER_SEND, AUFTRAG_ERTEILEN, PUSH_INSURANCE, BESTAETIGUNG_SENDEN, RECHNUNG_SENDEN, REMOVE_ORDER, AUFTRAG_WEITERLEITEN,PUSH_MAHNUNG, PUSH_DETAILS;

}
